
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&family=Noto+Serif+SC:wght@200;300;400;500;600;700;900&display=swap # for font

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  # Github: https://github.com/yours
  # Codepen: https://codepen.io/yours
  # Dribbble: https://dribbble.com/yours
  Bio: https://toosadtowrite.com
  Project IF: https://if.toosadtowrite.com
  Podcast: https://translate-slow.com
  # X: https://twitter.com/caeiro712
  Photography: https://iam.toosadtowrite.com/
  # 知乎: https://www.zhihu.com/yours
  # 掘金: https://juejin.im/user/yours
  Mail: mailto:work@toosadtowrite.com
  # and more, you can add other link by the same way
  RSS: atom.xml

# Uncomment to disable sidebar
toc: true
link: true
archives: true
categories: false
tags: true

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: G-SDQWZBXCKN

# comment module
comment:
  enable: false
  type: valine # valine | utterances

  # valine 需要的参数
  appId: your-app-id
  appKey: your-app-key
  placeholder: say something
  notify: false
  verify: false
  avatar: mp

  # utterances (https://utteranc.es/) 需要的参数
  repo: your-repo-name
  issue_term: your-issue-term
  theme: your-comment-theme
